#!/bin/bash

# VPN Server settings
REMOTE_HOSTNAME=128.199.95.172
REMOTE_USER=root
REMOTE_CONFIG_LOCATION=/root/myvpn

# VPN Client settings
LOCAL_CONFIG_LOCATION=/Users/manu.manjunath/myvpn

# Common settings
VPN_SERVER_NAME=gargantua
