#!/bin/bash

# VPN Server settings
REMOTE_HOSTNAME=8.8.8.8 # Remote machine ip address (where you want to install VPN server)
REMOTE_USER=root
REMOTE_CONFIG_LOCATION=/root/myvpn

# VPN Client settings
LOCAL_CONFIG_LOCATION=/Users/<your-user-name>/myvpn # Any local directory of your choice would do

# Common settings
VPN_SERVER_NAME=gargantua21 # Just a name
