#!/bin/bash

# VPN Server settings
REMOTE_HOSTNAME=172.217.160.142 # Create an AWS or Rackspace instance and specify the instance's ip address here 
REMOTE_USER=root
REMOTE_CONFIG_LOCATION=/root/myvpn

# VPN Client settings
LOCAL_CONFIG_LOCATION=/Users/manu.manjunath/myvpn

# Common settings
VPN_SERVER_NAME=gargantua # Just a name of your choice
